[tool.black]
line-length = 100
skip-magic-trailing-comma = true
target-version = ['py310']
include = '\.pyi?$'
force-exclude = '''
(
  /(
    | data
  )/
)
'''

[tool.darglint]
# darglint configuration:
# https://github.com/terrencepreilly/darglint
strictness = "long"

[tool.flake8]
# Base flake8 configuration:
# https://flake8.pycqa.org/en/latest/user/configuration.html
ignore = ["W503", "E203"]
per-file-ignores = [
    '__init__.py:F401',
]

exclude = [
    '.git,',
    '__pycache__',
]
max-line-length = 100
show-source = true
statistics = true
doctests = true
inline-quotes = "double"
require_plugins = [
    'darglint',
    'flake8-bandit',
    'flake8-black',
    'flake8-isort',
    'flake8-pyproject==1.2.3',
]

[tool.isort]
# isort configuration:
# https://pycqa.github.io/isort/docs/configuration/profiles.html
profile = "black"
line_length = 100
skip = ["data"]
